#!/bin/bash

# Live Smoke Test Helper - Draft 29
# Prints the smoke test checklist and key URLs for manual verification
# Does NOT automate any destructive actions or require backend changes

LIVE_URL="https://radicaleconomist101-h78.caffeine.xyz"

echo ""
echo "=========================================="
echo "Live Smoke Test Helper - Draft 29"
echo "=========================================="
echo ""
echo "This helper provides the smoke test checklist and key URLs."
echo "Follow the manual checklist in frontend/docs/live-smoke-test-v29.md"
echo ""
echo "⚠️  NOTE: This script does NOT automate tests"
echo "   Manual verification is required for accurate results"
echo ""

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Key URLs for Testing${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${CYAN}Live Site:${NC}      $LIVE_URL"
echo -e "${CYAN}Catalog:${NC}        $LIVE_URL/catalog"
echo -e "${CYAN}Cart:${NC}           $LIVE_URL/cart"
echo -e "${CYAN}Checkout:${NC}       $LIVE_URL/checkout"
echo -e "${CYAN}Library:${NC}        $LIVE_URL/library"
echo -e "${CYAN}Admin:${NC}          $LIVE_URL/admin"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Critical Verification Steps${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}1. Environment Badge Verification${NC}"
echo "   - Visit: $LIVE_URL"
echo "   - Check: Header shows 'Live' badge (not 'Draft')"
echo "   - Expected: Badge displays 'Live'"
echo ""
echo -e "${YELLOW}2. GLDT Wallet Address Verification${NC}"
echo "   - Navigate to checkout or wallet info section"
echo "   - Check: Wallet address matches Draft 29"
echo "   - Expected: Address matches Draft 29 exactly"
echo ""
echo -e "${YELLOW}3. Catalog Verification${NC}"
echo "   - Visit: $LIVE_URL/catalog"
echo "   - Check: Books display with correct titles, authors, prices"
echo "   - Check: Cover images load (ExternalBlob direct URLs)"
echo "   - Expected: All books render correctly"
echo ""
echo -e "${YELLOW}4. Book Details Verification${NC}"
echo "   - Click on a book from catalog"
echo "   - Check: Cover image, description, price display"
echo "   - Check: Add to Cart button works"
echo "   - Expected: Book details page fully functional"
echo ""
echo -e "${YELLOW}5. Purchase Flow Verification${NC}"
echo "   - Add book to cart → View cart → Checkout → Confirm"
echo "   - Check: Cart total calculates correctly"
echo "   - Check: KYC verification for restricted books"
echo "   - Expected: Purchase completes successfully"
echo ""
echo -e "${YELLOW}6. Library Verification${NC}"
echo "   - Visit: $LIVE_URL/library"
echo "   - Check: Purchased books appear"
echo "   - Check: Cover images load"
echo "   - Expected: Library displays all purchased books"
echo ""
echo -e "${YELLOW}7. PDF Download Verification${NC}"
echo "   - In library, click PDF download icon"
echo "   - Check: PDF downloads successfully"
echo "   - Expected: PDF opens and displays correctly"
echo ""
echo -e "${YELLOW}8. Admin Dashboard Verification (Admin Only)${NC}"
echo "   - Visit: $LIVE_URL/admin"
echo "   - Check: All tabs load (Catalog, Orders, Mint, Support, Settings)"
echo "   - Expected: Admin dashboard fully functional"
echo ""
echo -e "${YELLOW}9. ExternalBlob Direct URL Validation${NC}"
echo "   - Open browser dev tools (F12)"
echo "   - Inspect book cover image element"
echo "   - Check: Image src uses direct URL (not blob: or data:)"
echo "   - Expected: Using ExternalBlob.getDirectURL()"
echo ""
echo -e "${YELLOW}10. Cross-Browser Testing${NC}"
echo "   - Test in: Chrome, Firefox, Safari, Edge"
echo "   - Check: Environment badge shows 'Live' in all browsers"
echo "   - Expected: Site works correctly in all browsers"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Failure Capture${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "For any failures, record:"
echo "  - URL: (which page)"
echo "  - Step: (what you were doing)"
echo "  - Expected: (what should happen)"
echo "  - Observed: (what actually happened)"
echo "  - Console Errors: (any errors in browser console)"
echo ""
echo "See frontend/docs/live-smoke-test-v29.md for detailed templates"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Documentation${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}Full Smoke Test Checklist:${NC}"
echo "  frontend/docs/live-smoke-test-v29.md"
echo ""
echo -e "${GREEN}Publish Workflow Documentation:${NC}"
echo "  frontend/docs/publish-live.md"
echo ""
echo -e "${GREEN}Preflight Checks Documentation:${NC}"
echo "  frontend/docs/deployment-preflight.md"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Next Steps${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "1. Open the full checklist:"
echo "   cat frontend/docs/live-smoke-test-v29.md"
echo ""
echo "2. Visit the Live site:"
echo "   $LIVE_URL"
echo ""
echo "3. Follow each verification step in the checklist"
echo ""
echo "4. Record any failures using the provided templates"
echo ""
echo "5. Report results and follow up on any issues"
echo ""
echo -e "${GREEN}Good luck with your smoke tests!${NC}"
echo ""
