/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const KYcState = IDL.Variant({
  'awaitingProof' : IDL.Null,
  'validatedProof' : IDL.Null,
  'permanentlyBlacklisted' : IDL.Null,
  'rejected' : IDL.Null,
  'notRequired' : IDL.Null,
});
export const Time = IDL.Int;
export const CartItem = IDL.Record({
  'bookId' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'user' : IDL.Principal,
  'orderId' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(CartItem),
  'deliveredBookIds' : IDL.Vec(IDL.Text),
});
export const CustomerMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'responseToMsgId' : IDL.Opt(IDL.Nat),
  'isAdminResponse' : IDL.Bool,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MediaContent = IDL.Record({
  'pdf' : IDL.Opt(ExternalBlob),
  'audio' : IDL.Vec(ExternalBlob),
  'video' : IDL.Vec(ExternalBlob),
  'images' : IDL.Vec(ExternalBlob),
});
export const Book = IDL.Record({
  'id' : IDL.Text,
  'media' : MediaContent,
  'title' : IDL.Text,
  'content' : IDL.Opt(IDL.Text),
  'author' : IDL.Text,
  'available' : IDL.Bool,
  'kycRestricted' : IDL.Bool,
  'singleCopy' : IDL.Bool,
  'price' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OwnedBook = IDL.Record({
  'bookId' : IDL.Text,
  'purchasedBy' : IDL.Text,
});
export const CatalogState = IDL.Record({
  'purchasesByCustomerId' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
  'balanceStore' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
  'cartStore' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CartItem))),
  'nextMessageId' : IDL.Nat,
  'principalToKycId' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
  'supportMessages' : IDL.Vec(IDL.Tuple(IDL.Nat, CustomerMessage)),
  'bookStore' : IDL.Vec(IDL.Tuple(IDL.Text, Book)),
  'permanentlyBlacklisted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Null)),
  'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
  'ownedBooks' : IDL.Vec(IDL.Tuple(IDL.Text, OwnedBook)),
  'orderStore' : IDL.Vec(IDL.Tuple(IDL.Text, Order)),
  'kycRestrictedPurchases' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'designatedOwner' : IDL.Opt(IDL.Principal),
  'kycIdToPrincipal' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
  'validationTimestamps' : IDL.Vec(IDL.Tuple(IDL.Text, Time)),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBook' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blacklistKyc' : IDL.Func([IDL.Text], [KYcState], []),
  'checkout' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool],
      [IDL.Text, IDL.Opt(Order)],
      [],
    ),
  'deleteBook' : IDL.Func([IDL.Text], [], []),
  'exportCatalog' : IDL.Func([], [CatalogState], []),
  'fetchPurchasedBookMedia' : IDL.Func(
      [IDL.Text, IDL.Text],
      [MediaContent],
      ['query'],
    ),
  'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAvailableBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getDesignatedOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getKycProof' : IDL.Func([IDL.Text], [KYcState], []),
  'getMessageResponses' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CustomerMessage)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getPurchasedBookContent' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getUserMessages' : IDL.Func(
      [IDL.Bool],
      [IDL.Vec(CustomerMessage)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importCatalog' : IDL.Func([CatalogState], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'mintTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'recoverAdminAccess' : IDL.Func([], [], []),
  'rejectKycProof' : IDL.Func([IDL.Text], [KYcState], []),
  'removeBookAudio' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeBookImage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeBookPdf' : IDL.Func([IDL.Text], [], []),
  'removeBookVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeFromCart' : IDL.Func([IDL.Text], [], []),
  'resetStore' : IDL.Func([], [], []),
  'respondToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendSupportMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'setDesignatedOwner' : IDL.Func([IDL.Principal], [], []),
  'submitKycProof' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
  'updateBook' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updateBookContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadBookAudio' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadBookImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadBookPdf' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadBookVideo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const KYcState = IDL.Variant({
    'awaitingProof' : IDL.Null,
    'validatedProof' : IDL.Null,
    'permanentlyBlacklisted' : IDL.Null,
    'rejected' : IDL.Null,
    'notRequired' : IDL.Null,
  });
  const Time = IDL.Int;
  const CartItem = IDL.Record({ 'bookId' : IDL.Text, 'quantity' : IDL.Nat });
  const Order = IDL.Record({
    'user' : IDL.Principal,
    'orderId' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(CartItem),
    'deliveredBookIds' : IDL.Vec(IDL.Text),
  });
  const CustomerMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'responseToMsgId' : IDL.Opt(IDL.Nat),
    'isAdminResponse' : IDL.Bool,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MediaContent = IDL.Record({
    'pdf' : IDL.Opt(ExternalBlob),
    'audio' : IDL.Vec(ExternalBlob),
    'video' : IDL.Vec(ExternalBlob),
    'images' : IDL.Vec(ExternalBlob),
  });
  const Book = IDL.Record({
    'id' : IDL.Text,
    'media' : MediaContent,
    'title' : IDL.Text,
    'content' : IDL.Opt(IDL.Text),
    'author' : IDL.Text,
    'available' : IDL.Bool,
    'kycRestricted' : IDL.Bool,
    'singleCopy' : IDL.Bool,
    'price' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OwnedBook = IDL.Record({
    'bookId' : IDL.Text,
    'purchasedBy' : IDL.Text,
  });
  const CatalogState = IDL.Record({
    'purchasesByCustomerId' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Vec(IDL.Text))),
    'balanceStore' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat)),
    'cartStore' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CartItem))),
    'nextMessageId' : IDL.Nat,
    'principalToKycId' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Text)),
    'supportMessages' : IDL.Vec(IDL.Tuple(IDL.Nat, CustomerMessage)),
    'bookStore' : IDL.Vec(IDL.Tuple(IDL.Text, Book)),
    'permanentlyBlacklisted' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Null)),
    'userProfiles' : IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile)),
    'ownedBooks' : IDL.Vec(IDL.Tuple(IDL.Text, OwnedBook)),
    'orderStore' : IDL.Vec(IDL.Tuple(IDL.Text, Order)),
    'kycRestrictedPurchases' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'designatedOwner' : IDL.Opt(IDL.Principal),
    'kycIdToPrincipal' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Principal)),
    'validationTimestamps' : IDL.Vec(IDL.Tuple(IDL.Text, Time)),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBook' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'addToCart' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blacklistKyc' : IDL.Func([IDL.Text], [KYcState], []),
    'checkout' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool],
        [IDL.Text, IDL.Opt(Order)],
        [],
      ),
    'deleteBook' : IDL.Func([IDL.Text], [], []),
    'exportCatalog' : IDL.Func([], [CatalogState], []),
    'fetchPurchasedBookMedia' : IDL.Func(
        [IDL.Text, IDL.Text],
        [MediaContent],
        ['query'],
      ),
    'getAllBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAvailableBooks' : IDL.Func([], [IDL.Vec(Book)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getBook' : IDL.Func([IDL.Text], [Book], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getDesignatedOwner' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
    'getKycProof' : IDL.Func([IDL.Text], [KYcState], []),
    'getMessageResponses' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CustomerMessage)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getPurchasedBookContent' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getUserMessages' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(CustomerMessage)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importCatalog' : IDL.Func([CatalogState], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'mintTokens' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'recoverAdminAccess' : IDL.Func([], [], []),
    'rejectKycProof' : IDL.Func([IDL.Text], [KYcState], []),
    'removeBookAudio' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeBookImage' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeBookPdf' : IDL.Func([IDL.Text], [], []),
    'removeBookVideo' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeFromCart' : IDL.Func([IDL.Text], [], []),
    'resetStore' : IDL.Func([], [], []),
    'respondToMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendSupportMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'setDesignatedOwner' : IDL.Func([IDL.Principal], [], []),
    'submitKycProof' : IDL.Func([IDL.Text, IDL.Bool], [IDL.Text], []),
    'updateBook' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updateBookContent' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadBookAudio' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadBookImage' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadBookPdf' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadBookVideo' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };