/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Book {
  'id' : string,
  'pdf' : [] | [ExternalBlob],
  'title' : string,
  'content' : [] | [string],
  'author' : string,
  'available' : boolean,
  'price' : bigint,
}
export interface CartItem { 'bookId' : string, 'quantity' : bigint }
export interface CustomerMessage {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'responseToMsgId' : [] | [bigint],
  'isAdminResponse' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface Order {
  'user' : Principal,
  'orderId' : string,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<CartItem>,
  'deliveredBookIds' : Array<string>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBook' : ActorMethod<
    [string, string, string, bigint, [] | [string]],
    undefined
  >,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkout' : ActorMethod<[string], undefined>,
  'deleteBook' : ActorMethod<[string], undefined>,
  'fetchPurchasedBookPdf' : ActorMethod<[string, string], [] | [ExternalBlob]>,
  'getAllBooks' : ActorMethod<[], Array<Book>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableBooks' : ActorMethod<[], Array<Book>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getBook' : ActorMethod<[string], Book>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDesignatedOwner' : ActorMethod<[], [] | [Principal]>,
  'getMessageResponses' : ActorMethod<[bigint], Array<CustomerMessage>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getPurchasedBookContent' : ActorMethod<[string, string], [] | [string]>,
  'getUserMessages' : ActorMethod<[boolean], Array<CustomerMessage>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'mintTokens' : ActorMethod<[Principal, bigint], undefined>,
  'recoverAdminAccess' : ActorMethod<[], undefined>,
  'removeBookPdf' : ActorMethod<[string], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'resetStore' : ActorMethod<[], undefined>,
  'respondToMessage' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendSupportMessage' : ActorMethod<[string], bigint>,
  'setDesignatedOwner' : ActorMethod<[Principal], undefined>,
  'updateBook' : ActorMethod<
    [string, string, string, bigint, boolean],
    undefined
  >,
  'updateBookContent' : ActorMethod<[string, string], undefined>,
  'uploadBookPdf' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];